backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  
  - name: "career"
    label: "Career"
    folder: "src/pages/career"
    create: true
    slug: "{{slug}}"
    fields:
    - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "career-offer",
      }
    - { label: "Title", name: "title", widget: "string" }
    - { 
        label: "Vacancies", 
        name: "vacancies", 
        widget: "list",
        allow_add: true, 
        label_singular: "vacancy", 
        field: { label: Vacancy, name: vacancy, widget: string } 
      }
    - { 
        label: "Types of contract", 
        name: "typesOfContract", 
        widget: "list", 
        allow_add: true, 
        label_singular: "contract", 
        field: { label: Contract, name: contract, widget: string } 
      }
    - { 
        label: "Responsibilities", 
        name: "responsibilities", 
        widget: "list",
        allow_add: true, 
        label_singular: "responsibility", 
        field: { label: Responsibility, name: responsibility, widget: string }  
      }
    - { 
        label: "Requirements", 
        name: "requirements", 
        widget: "list" ,
        allow_add: true, 
        label_singular: "requirement", 
        field: { label: Requirement, name: requirement , widget: string } 
      }
    - { 
        label: "What we offer", 
        name: "whatWeOffer", 
        widget: "list",
        allow_add: true, 
        label_singular: "offer", 
        field: {label: Offer, name: offer, widget: string} 
      }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/privacy-policy/index.md"
        label: "Privacy Policy Page"
        name: "privacy-policy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy-policy-page",
          }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - file: "src/pages/terms-and-conditions/index.md"
        label: "Terms And Conditions Page"
        name: "terms-and-conditions"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "terms-and-conditions-page",
          }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { 
              label: Carousel Items, 
              name: carouselItems, 
              widget: list,
              allow_add: true, 
              label_singular: "item", 
              field: { label: Image, name: image, widget: image } 
            }
 
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/product/index.md"
        label: "Prodcut"
        name: "product"
        fields:
          - { 
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page"
            }
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Content Section Title", name: "contentSectionTitle", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }